package moe.majsoulmax.app.core

import moe.majsoulmax.app.data.TunnelSettings

/**
 * Builds the hev-socks5-tunnel configuration.
 *
 * The tun device itself is passed as a file descriptor rather than by name, so
 * `tunnel.name` is deliberately absent: the descriptor always wins and naming it
 * would only invite confusion.
 */
object Tun2SocksConfig {

    /** Address handed to the tun interface; also the tunnel's own gateway. */
    const val TUN_ADDRESS = "198.18.0.1"
    const val TUN_PREFIX = 30
    const val TUN_ADDRESS_V6 = "fdfe:dcba:9876::1"
    const val TUN_PREFIX_V6 = 126

    fun build(settings: TunnelSettings): String {
        val s = settings.sanitised()
        return buildString {
            appendLine("# Generated by Majsoul Max")
            appendLine("tunnel:")
            appendLine("  mtu: ${s.mtu}")
            appendLine("  ipv4: $TUN_ADDRESS")
            if (s.ipv6) appendLine("  ipv6: '$TUN_ADDRESS_V6'")
            appendLine("socks5:")
            appendLine("  address: 127.0.0.1")
            appendLine("  port: ${s.mixedPort}")
            // UDP over SOCKS5 UDP-ASSOCIATE, which the kernel's mixed port
            // supports and DNS through the tunnel depends on.
            appendLine("  udp: 'udp'")
            appendLine("  mark: 0")
            appendLine("misc:")
            appendLine("  task-stack-size: 20480")
            appendLine("  connect-timeout: 5000")
            appendLine("  read-write-timeout: 60000")
            appendLine("  log-level: ${hevLogLevel(s.kernelLogLevel)}")
            appendLine("  limit-nofile: 65535")
        }
    }

    /** hev only knows debug/info/warn/error; map the kernel's vocabulary onto it. */
    private fun hevLogLevel(kernelLevel: String): String = when (kernelLevel) {
        "debug" -> "debug"
        "info" -> "info"
        "silent", "error" -> "error"
        else -> "warn"
    }
}
