package moe.majsoulmax.app.core

import moe.majsoulmax.app.data.TunnelSettings

/**
 * Builds the hev-socks5-tunnel configuration.
 *
 * The tun device itself is passed as a file descriptor rather than by name, so
 * `tunnel.name` is deliberately absent: the descriptor always wins and naming it
 * would only invite confusion.
 */
object Tun2SocksConfig {

    /**
     * Address handed to the tun interface; also the tunnel's own gateway.
     *
     * Deliberately NOT `198.18.0.1/30`: that is the convention shared by Clash,
     * mihomo, v2ray's tun2socks and hev-socks5-tunnel itself, and Clash's default
     * fake-ip range overlays it. When another tool's tun already owns that
     * subnet, the OS sources this app's own outbound sockets from the foreign
     * interface and every upstream connection times out, which reads as "the
     * game has no network" with nothing in the log but i/o timeouts. `172.19` is
     * sing-box's documented example, so this sits outside both conventions while
     * staying private — which is also what keeps it out of the VPN's own routes.
     */
    const val TUN_ADDRESS = "172.20.0.1"
    const val TUN_PREFIX = 30

    /** Likewise away from Clash's documented `fdfe:dcba:9876::1/126`. */
    const val TUN_ADDRESS_V6 = "fd7a:6d61:6a73::1"
    const val TUN_PREFIX_V6 = 126

    fun build(settings: TunnelSettings): String {
        val s = settings.sanitised()
        return buildString {
            appendLine("# Generated by Majsoul Max")
            appendLine("tunnel:")
            appendLine("  mtu: ${s.mtu}")
            appendLine("  ipv4: $TUN_ADDRESS")
            if (s.ipv6) appendLine("  ipv6: '$TUN_ADDRESS_V6'")
            appendLine("socks5:")
            appendLine("  address: 127.0.0.1")
            appendLine("  port: ${s.mixedPort}")
            // UDP over SOCKS5 UDP-ASSOCIATE, which the kernel's mixed port
            // supports and DNS through the tunnel depends on.
            appendLine("  udp: 'udp'")
            appendLine("  mark: 0")
            appendLine("misc:")
            appendLine("  task-stack-size: 20480")
            appendLine("  connect-timeout: 5000")
            appendLine("  read-write-timeout: 60000")
            appendLine("  log-level: ${hevLogLevel(s.kernelLogLevel)}")
            appendLine("  limit-nofile: 65535")
        }
    }

    /** hev only knows debug/info/warn/error; map the kernel's vocabulary onto it. */
    private fun hevLogLevel(kernelLevel: String): String = when (kernelLevel) {
        "debug" -> "debug"
        "info" -> "info"
        "silent", "error" -> "error"
        else -> "warn"
    }
}
